#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : KD and Tokyo's air sources  # The title of the book. Will be placed in the left navbar.
author                      : Alejandro Fontal  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : images/logo.png # A path to the book logo

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/AlFontal/vasculitis2022-conference
html:
  use_repository_button: true
  use_issues_button: true
  favicon: images/favicon.ico
  baseurl: 'https://alfontal.github.io/vasculitis2022-conference'
  comments:
    utterances: 
      repo: 'AlFontal/vasculitis2022-conference'


sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
