# yaml-language-server: $schema=./_config.yaml
#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : KD and Tokyo's air sources  # The title of the book. Will be placed in the left navbar.
author                      : Alejandro Fontal  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : images/logo.png # A path to the book logo

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/AlFontal/vasculitis2022-conference
html:
  use_repository_button: true
  use_issues_button: true
  favicon: images/favicon.ico
  baseurl: 'https://alfontal.github.io/vasculitis2022-conference'
  comments:
    utterances: 
      repo: 'AlFontal/vasculitis2022-conference'
  extra_navbar: |
            <hr>
            <a href="https://vasculitis2022.org/">
            <img src="https://vasculitis2022.org/wp-content/uploads/2020/10/Vasculitis-2022.png" width=200px>
            </a>
            <hr>
            <a href="https://helical-itn.eu/">
            <img src="https://helical-itn.eu/wp-content/uploads/2020/01/cropped-HELICAL_logo-3.png" width=200px>
            </a>
            <hr>
            <a href="https://www.isglobal.org/en/-/clima-y-salud">
            <img src="https://www.isglobal.org/isglobal-new-theme/assets/images/isglobal/logo-isglobal-en.png" width=200px>
            </a>
            <hr>

bibtex_bibfiles: references.bib

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
